GET http://localhost:5000/users/id/transactions?limit=8&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjcmVhdGl2ZWZuIiwidXNlcklkIjoyLCJyb2xlIjoiY3JlYXRvciIsImxhc3ROYW1lIjoiY3JlYXRpdmVsbiIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJjcmVhdGl2ZWRuIiwiYmFsYW5jZSI6IjEwMCIsImVtYWlsIjoiY3JlYXRpdmVAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3MzIzNzYyODUsImV4cCI6MTczMjM3OTg4NX0.CMdbhazXX5zcpYq5UYZz3yrkjbb6iidtToZFVseUDEQ